In [205]:
import pyodbc
import urllib.request
import requests
import pandas as pd
import numpy as np
from io import StringIO

In [ ]:
#target url: https://www1.ncdc.noaa.gov/pub/data/ghcn/daily/ghcnd-stations.txt
with urllib.request.urlopen("https://www1.ncdc.noaa.gov/pub/data/ghcn/daily/ghcnd-stations.txt") as url:
    s = url.read()

In [217]:
n = '\n'
bn = bytes(n,encoding='utf-8')
s.split(bn)

s = str(s,'utf-8')
data = StringIO(s)
df = pd.read_csv(data,sep=",")

TypeError: must be str or None, not bytes

In [149]:


#data = csvToArray('https://www.ncei.noaa.gov/access/services/data/v1?dataset=daily-summaries&dataTypes=WIND_SPEED,TMAX,TMIN,PRCP&stations=USC00047821&startDate=1900-10-01&endDate=2019-11-01&format=csv')

pd.read_csv('https://www.ncei.noaa.gov/access/services/data/v1?dataset=daily-summaries&dataTypes=WIND_SPEED,TMAX,TMIN,PRCP&stations=USC00457180,USC00390043&startDate=1900-10-01&endDate=2019-11-01&format=csv')

           STATION        DATE   PRCP   TMAX   TMIN  WIND_SPEED
0      USC00457180  1900-10-01    0.0  117.0   11.0         NaN
1      USC00457180  1900-10-02    0.0  122.0   17.0         NaN
2      USC00457180  1900-10-03  107.0  106.0   44.0         NaN
3      USC00457180  1900-10-04    8.0  111.0   22.0         NaN
4      USC00457180  1900-10-05   76.0  100.0   50.0         NaN
5      USC00457180  1900-10-06    0.0  100.0    6.0         NaN
6      USC00457180  1900-10-07    0.0  161.0    0.0         NaN
7      USC00457180  1900-10-08    0.0  200.0   22.0         NaN
8      USC00457180  1900-10-09    0.0  183.0    0.0         NaN
9      USC00457180  1900-10-10   33.0  133.0   67.0         NaN
10     USC00457180  1900-10-11    0.0  167.0   -6.0         NaN
11     USC00457180  1900-10-12    0.0  167.0    0.0         NaN
12     USC00457180  1900-10-13    0.0  183.0   28.0         NaN
13     USC00457180  1900-10-14    0.0  172.0   89.0         NaN
14     USC00457180  1900-10-15    0.0  222.0   33.0         NaN
15     USC00457180  1900-10-16    0.0  233.0   33.0         NaN
16     USC00457180  1900-10-17    0.0  239.0   67.0         NaN
17     USC00457180  1900-10-18  107.0  156.0   89.0         NaN
18     USC00457180  1900-10-19  122.0  133.0   44.0         NaN
19     USC00457180  1900-10-20   38.0  122.0   39.0         NaN
20     USC00457180  1900-10-21   23.0  172.0   67.0         NaN
21     USC00457180  1900-10-22   20.0  106.0   56.0         NaN
22     USC00457180  1900-10-23    0.0   89.0   11.0         NaN
23     USC00457180  1900-10-24   20.0   61.0   17.0         NaN
24     USC00457180  1900-10-25   76.0   61.0   11.0         NaN
25     USC00457180  1900-10-26    0.0   89.0   11.0         NaN
26     USC00457180  1900-10-27   18.0  100.0  -17.0         NaN
27     USC00457180  1900-10-28   51.0   78.0   33.0         NaN
28     USC00457180  1900-10-29   13.0   67.0   11.0         NaN
29     USC00457180  1900-10-30   25.0   67.0   -6.0         NaN
...            ...         ...    ...    ...    ...         ...
86393  USC00390043  2019-10-03   15.0   72.0   39.0         NaN
86394  USC00390043  2019-10-04    0.0  111.0   22.0         NaN
86395  USC00390043  2019-10-05   15.0  117.0   44.0         NaN
86396  USC00390043  2019-10-06    0.0  172.0   39.0         NaN
86397  USC00390043  2019-10-07    0.0  183.0   33.0         NaN
86398  USC00390043  2019-10-08    0.0  239.0   50.0         NaN
86399  USC00390043  2019-10-09    0.0  239.0  106.0         NaN
86400  USC00390043  2019-10-10   81.0  133.0    6.0         NaN
86401  USC00390043  2019-10-11   91.0    6.0  -28.0         NaN
86402  USC00390043  2019-10-12    0.0   22.0  -22.0         NaN
86403  USC00390043  2019-10-13    0.0   67.0    0.0         NaN
86404  USC00390043  2019-10-14    0.0   94.0  -22.0         NaN
86405  USC00390043  2019-10-15    0.0  178.0    6.0         NaN
86406  USC00390043  2019-10-16    0.0   83.0   11.0         NaN
86407  USC00390043  2019-10-17    0.0  128.0    6.0         NaN
86408  USC00390043  2019-10-18    0.0  200.0   33.0         NaN
86409  USC00390043  2019-10-19    0.0  183.0   22.0         NaN
86410  USC00390043  2019-10-20    0.0  178.0   33.0         NaN
86411  USC00390043  2019-10-21   46.0  139.0   56.0         NaN
86412  USC00390043  2019-10-22   38.0   78.0    6.0         NaN
86413  USC00390043  2019-10-23    8.0  128.0   17.0         NaN
86414  USC00390043  2019-10-24    0.0   44.0  -44.0         NaN
86415  USC00390043  2019-10-25    0.0   94.0   -6.0         NaN
86416  USC00390043  2019-10-26    0.0  183.0   28.0         NaN
86417  USC00390043  2019-10-27    0.0  178.0  -11.0         NaN
86418  USC00390043  2019-10-28    0.0   17.0  -72.0         NaN
86419  USC00390043  2019-10-29    0.0   33.0  -67.0         NaN
86420  USC00390043  2019-10-30    0.0  -17.0  -94.0         NaN
86421  USC00390043  2019-10-31    0.0  -11.0 -100.0         NaN
86422  USC00390043  2019-11-01    0.0   83.0  -67.0         NaN

[86423 rows x 6 columns]

In [151]:
conn = pyodbc.connect('Driver={SQL Server};'
                      'Server=LAPTOP-RC2ANL8F\SQLEXPRESS;'
                      'Database=WeatherWars;'
                      'Trusted_Connection=yes;')

In [158]:
cursor = conn.cursor()

In [168]:
cursor.execute('SELECT * FROM WeatherWars.dbo.player')

In [169]:
for row in cursor:
    print(row)

('o', 'o', '1995-11-15', 'o', '4')
('omri', 'easypass', '1995-11-15', 'omrilevia@gmail.com', '4087813509')

In [170]:
command = 'INSERT INTO WeatherWars.dbo.player VALUES(\'o\',\'o\',\'1995-11-15\',\'o\',\'4\')'

In [171]:
cursor.execute(command)

IntegrityError: ('23000', "[23000] [Microsoft][ODBC SQL Server Driver][SQL Server]Violation of PRIMARY KEY constraint 'PK__player__66DCF95D68DB09AB'. Cannot insert duplicate key in object 'dbo.player'. The duplicate key value is (o). (2627) (SQLExecDirectW); [23000] [Microsoft][ODBC SQL Server Driver][SQL Server]The statement has been terminated. (3621)")

In [172]:
cursor.execute('SELECT * FROM WeatherWars.dbo.player')

In [173]:
for row in cursor:
    print(row)

('o', 'o', '1995-11-15', 'o', '4')
('omri', 'easypass', '1995-11-15', 'omrilevia@gmail.com', '4087813509')